# file: nginx/tasks/modules/http_auth_request_module.yml
# configure flag: --add-module={{nginx_build_dir}}/nginx_auth_request

- name: Nginx Install | Modules | Download the http_auth_request_module source
  get_url:
    url: "{{nginx_auth_request_url}}"
    dest: "{{nginx_build_dir}}/nginx-auth-request-module-{{nginx_auth_request_release}}.tar.gz"

- name: Nginx Install | Modules | Unpack the http_auth_request_module source
  command: "tar -xvzf {{nginx_build_dir}}/nginx-auth-request-module-{{nginx_auth_request_release}}.tar.gz"
  args: 
    chdir:   "{{nginx_build_dir}}"
    creates: "{{nginx_build_dir}}/ngx_http_auth_request_module-{{nginx_auth_request_release}}"
