# file: nginx/tasks/modules/ngx_pagespeed.yml
# configure flag: --add-module={{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta

- name: Nginx Install | Modules | Make sure the dependences are installed
  apt:
    pkg: "{{item}}"
  with_items:
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev

- name: Nginx Install | Modules | Download the ngx_pagespeed source
  get_url:
    url: "https://github.com/pagespeed/ngx_pagespeed/archive/release-{{nginx_ngx_pagespeed_version}}-beta.tar.gz"
    dest: "{{nginx_build_dir}}/ngx_pagespeed_module-{{nginx_ngx_pagespeed_version}}.tar.gz"

- name: Nginx Install | Modules | Unpack the ngx_pagespeed source
  command: "tar -xvzf '{{nginx_build_dir}}/ngx_pagespeed_module-{{nginx_ngx_pagespeed_version}}.tar.gz'"
  args:
    chdir: "{{nginx_build_dir}}"
    creates: "{{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta"

- name: Nginx Install | Modules | Download the psol source
  get_url:
    url: "https://dl.google.com/dl/page-speed/psol/{{nginx_ngx_pagespeed_version}}.tar.gz"
    dest: "{{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta/psol-{{nginx_ngx_pagespeed_version}}.tar.gz"

- name: Nginx Install | Modules | Unpack the psol source
  command: "tar -xvzf {{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta/psol-{{nginx_ngx_pagespeed_version}}.tar.gz"
  args:
    chdir: "{{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta"
    creates: "{{nginx_build_dir}}/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta/psol"
