# file: nginx/handlers/main.yml

- name:    restart nginx
  service: name=nginx state=restarted
  become:  yes

- name:    reload nginx
  service: name=nginx state=reloaded
  become:  yes

- name:    restart monit
  service: name=monit state=restarted
  become:  yes
